### ISSUE TITLE
cuFFT_INTERNAL_ERROR during fine-tuning Piper

### ISSUE THREAD

**Issue by souadkhalifeh** [OHF-Voice/piper1-gpl#139]
When attempting to fine-tune an Arabic-based Piper voice (Kareem , low) on my own dataset, training consistently crashes during mel-spectrogram computation with the following error:

`  File "/home/ubuntu/piper_finetuning/piper/src/python/.venv/lib/python3.10/site-packages/torch/functional.py", line 632, in stft
    return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]`
`RuntimeError: cuFFT error: CUFFT_INTERNAL_ERROR`

This issue occurs even when using older PyTorch versions (1.12.1, 1.13.1) and older CUDA versions (11.3, 11.7) 
Ive also tried different environments: 
- WSL2 (Ubuntu 22.04 and 24.04) with 8GB VRAM RTX 5060 and RTX 4050
- Fresh WSL installation 
- Cloud GPU Linux machine

Also if i have decreased the batch size, the error persists

**Comment by RasikhUrRehman** [comment]
I encountered the same error while training. This issue is not related to pytorh versions. It happens when the model allocates all the available memory during the Fourier Transform. 

It can be resolved by either lowering the batch size. (maybe 2,4). Or by clipping the GPU usage in pytorch.

Use command like following. It will clip the usage to 4 GB.

cd /home/natiq/projects/piper1-gpl/src && \
source ../.venv/bin/activate && \
PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512 \
python3 - <<'EOF'
import torch
total_gb = torch.cuda.get_device_properties(0).total_memory / 1024**3
fraction = 4 / total_gb
torch.cuda.set_per_process_memory_fraction(fraction, 0)
print(f"GPU memory limited to ~4GB ({fraction:.3f} of total {total_gb:.1f}GB)")
EOF

It worked for me. I hope it works for you too.
